version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12

    commands:
        - npm --prefix ./react-frontend install
       
  build:
    commands:
        - npm --prefix ./react-frontend run build
     
artifacts:
  files:
    - '**/*'
  base-directory: './react-frontend/build'
